routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return File::get(resource_path() . '/views/landing/index.html');
});

// Admin routes
Route::name('admin.')->prefix('admin')->namespace('Admin')->group(function () {
    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Login
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login');

        // Forget and reset Password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('forgot_password');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset/{token}/{email?}', 'ResetPasswordController@showResetForm')->name('reset_password_link');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('reset_password');
    });

    // Logged in admin user required
    Route::group(['middleware' => 'auth:admin'], function () {
        // Dashboard
        Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

        Route::resource('addresses', 'AddressController');

        Route::resource('categories', 'CategoryController');

        Route::resource('customers', 'CustomerController');

        Route::resource('products', 'ProductController');

        Route::resource('notifications', 'NotificationController');

        Route::resource('orders', 'OrderController');

        Route::resource('promos', 'PromoController');

        // Profile
        Route::get('/profile', 'AdminController@profile')->name('profile');
        Route::post('/profile', 'AdminController@profileUpdate');
        Route::post('/password', 'AdminController@passwordUpdate')->name('password_update');

        // Logout
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

app/Notification.php
<?php

namespace App;

use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Notification extends Model
{
    use SoftDeletes, LogsActivity;

    protected static $logFillable = true;

    protected static $logOnlyDirty = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'message', 'product_id', 'note'
    ];

    /**
     * Validation rules
     *
     * @return array
     **/
    public static function validationRules()
    {
        return [
            'message' => 'required|string',
            'product_id' => 'required|string',
            'note' => 'nullable|string',
        ];
    }

    /**
     * Returns the paginated list of resources
     *
     * @return \Illuminate\Pagination\Paginator
     **/
    public static function getList()
    {
        return static::paginate(10);
    }
}

app/Http/Controllers/Admin/NotificationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Notification;
use App\Http\Controllers\Controller;

class NotificationController extends Controller
{
    /**
     * Display a list of Notifications.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notifications = Notification::getList();

        return view('admin.notifications.index', compact('notifications'));
    }

    /**
     * Show the form for creating a new Notification
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.notifications.add');
    }

    /**
     * Save new Notification
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        $validatedData = request()->validate(Notification::validationRules());

        $notification = Notification::create($validatedData);

        return redirect()->route('admin.notifications.index')->with([
            'type' => 'success',
            'message' => 'Notification added'
        ]);
    }

    /**
     * Show the form for editing the specified Notification
     *
     * @param \App\Notification $notification
     * @return \Illuminate\Http\Response
     */
    public function edit(Notification $notification)
    {
        return view('admin.notifications.edit', compact('notification'));
    }

    /**
     * Update the Notification
     *
     * @param \App\Notification $notification
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Notification $notification)
    {
        $validatedData = request()->validate(
            Notification::validationRules($notification->id)
        );

        $notification->update($validatedData);

        return redirect()->route('admin.notifications.index')->with([
            'type' => 'success',
            'message' => 'Notification Updated'
        ]);
    }

    /**
     * Delete the Notification
     *
     * @param \App\Notification $notification
     * @return void
     */
    public function destroy(Notification $notification)
    {
        $notification->delete();

        return redirect()->route('admin.notifications.index')->with([
            'type' => 'success',
            'message' => 'Notification deleted successfully'
        ]);
    }
}

resources/views/admin/notifications/add.blade.php
@extends('admin.layouts.app', ['page' => 'notification'])

@section('title', 'Add New Notification')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Add New Notification
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" action="{{ route('admin.notifications.store') }}">
        @csrf

        <div class="form-group">
            <label for="message">Message</label>
            <input type="text"
                class="form-control"
                name="message"
                required
                placeholder="Message"
                value="{{ old('message') }}"
                id="message"
            >
        </div>

        <div class="form-group">
            <label for="product_id">Product Id</label>
            <input type="text"
                class="form-control"
                name="product_id"
                required
                placeholder="Product Id"
                value="{{ old('product_id') }}"
                id="product_id"
            >
        </div>

        <div class="form-group">
            <label for="note">Note</label>
            <textarea class="form-control"
                name="note"
                id="note"
                required
                placeholder="Note"
            >{{ old('note') }}</textarea>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Submit
            </button>

            <a class="btn btn-sm btn-danger"
                href="{{ route('admin.notifications.index') }}"
            >
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/notifications/edit.blade.php
@extends('admin.layouts.app', ['page' => 'notification'])

@section('title', 'Edit Notification')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Edit Notification
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" action="{{ route('admin.notifications.update', ['notification' => $notification->id]) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="message">Message</label>
            <input type="text"
                class="form-control"
                name="message"
                required
                placeholder="Message"
                value="{{ old('message', $notification->message) }}"
                id="message"
            >
        </div>

        <div class="form-group">
            <label for="product_id">Product Id</label>
            <input type="text"
                class="form-control"
                name="product_id"
                required
                placeholder="Product Id"
                value="{{ old('product_id', $notification->product_id) }}"
                id="product_id"
            >
        </div>

        <div class="form-group">
            <label for="note">Note</label>
            <textarea class="form-control"
                name="note"
                id="note"
                required
                placeholder="Note"
            >{{ old('note', $notification->note) }}</textarea>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Update
            </button>

            <a class="btn btn-sm btn-danger"
                href="{{ route('admin.notifications.index') }}"
            >
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/notifications/index.blade.php
@extends('admin.layouts.app', ['page' => 'notification'])

@section('title', 'Notifications')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Notifications
        </div>

        <div class="col-6 text-right">
            <a class="btn btn-md btn-square btn-secondary"
                href="{{ route('admin.notifications.create') }}"
            >
                Add New
            </a>
        </div>
    </div>
</div>

<div class="card-body m-2">
    <table class="table table-responsive-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Message</th>
                <th>Product Id</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($notifications as $notification)
                <tr>
                    <td>{{ $notification->id }}</td>
                    <td>{{ $notification->message }}</td>
                    <td>{{ $notification->product_id }}</td>
                    <td>
                        <a class="btn btn-pill btn-sm btn-warning"
                            href="{{ route('admin.notifications.edit', ['notification' => $notification->id]) }}"
                        >
                            <i class="fa fa-pencil-square-o"></i>
                        </a>

                        <form action="{{ route('admin.notifications.destroy', ['notification' => $notification->id]) }}"
                            method="POST"
                            class="inline pointer"
                        >
                            @csrf
                            @method('DELETE')

                            <a class="btn btn-pill btn-sm btn-danger"
                                onclick="if (confirm('Are you sure?')) { this.parentNode.submit() }"
                            >
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{ $notifications->links() }}
</div>
@endsection