routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return File::get(resource_path() . '/views/landing/index.html');
});

// Admin routes
Route::name('admin.')->prefix('admin')->namespace('Admin')->group(function () {
    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Login
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login');

        // Forget and reset Password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('forgot_password');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset/{token}/{email?}', 'ResetPasswordController@showResetForm')->name('reset_password_link');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('reset_password');
    });

    // Logged in admin user required
    Route::group(['middleware' => 'auth:admin'], function () {
        // Dashboard
        Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

        Route::resource('addresses', 'AddressController');

        Route::resource('categories', 'CategoryController');

        Route::resource('customers', 'CustomerController');

        Route::resource('products', 'ProductController');

        Route::resource('notifications', 'NotificationController');

        Route::resource('orders', 'OrderController');

        Route::resource('promos', 'PromoController');

        // Profile
        Route::get('/profile', 'AdminController@profile')->name('profile');
        Route::post('/profile', 'AdminController@profileUpdate');
        Route::post('/password', 'AdminController@passwordUpdate')->name('password_update');

        // Logout
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

app/Promo.php
<?php

namespace App;

use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Promo extends Model
{
    use SoftDeletes, LogsActivity;

    protected static $logFillable = true;

    protected static $logOnlyDirty = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code', 'discount', 'note'
    ];

    /**
     * Validation rules
     *
     * @return array
     **/
    public static function validationRules()
    {
        return [
            'code' => 'required|string',
            'discount' => 'required|numeric',
            'note' => 'required|string',
        ];
    }

    /**
     * Get the orders for the Promo.
     */
    public function orders()
    {
        return $this->hasMany('App\Order');
    }

    /**
     * Returns the paginated list of resources
     *
     * @return \Illuminate\Pagination\Paginator
     **/
    public static function getList()
    {
        return static::paginate(10);
    }
}

app/Http/Controllers/Admin/PromoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Promo;
use App\Http\Controllers\Controller;

class PromoController extends Controller
{
    /**
     * Display a list of Promos.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $promos = Promo::getList();

        return view('admin.promos.index', compact('promos'));
    }

    /**
     * Show the form for creating a new Promo
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.promos.add');
    }

    /**
     * Save new Promo
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        $validatedData = request()->validate(Promo::validationRules());

        $promo = Promo::create($validatedData);

        return redirect()->route('admin.promos.index')->with([
            'type' => 'success',
            'message' => 'Promo added'
        ]);
    }

    /**
     * Show the form for editing the specified Promo
     *
     * @param \App\Promo $promo
     * @return \Illuminate\Http\Response
     */
    public function edit(Promo $promo)
    {
        return view('admin.promos.edit', compact('promo'));
    }

    /**
     * Update the Promo
     *
     * @param \App\Promo $promo
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Promo $promo)
    {
        $validatedData = request()->validate(
            Promo::validationRules($promo->id)
        );

        $promo->update($validatedData);

        return redirect()->route('admin.promos.index')->with([
            'type' => 'success',
            'message' => 'Promo Updated'
        ]);
    }

    /**
     * Delete the Promo
     *
     * @param \App\Promo $promo
     * @return void
     */
    public function destroy(Promo $promo)
    {
        if ($promo->orders()->count()) {
            return redirect()->route('admin.promos.index')->with([
                'type' => 'error',
                'message' => 'This record cannot be deleted as there are relationship dependencies.'
            ]);
        }

        $promo->delete();

        return redirect()->route('admin.promos.index')->with([
            'type' => 'success',
            'message' => 'Promo deleted successfully'
        ]);
    }
}

app/Http/Controllers/Api/PromosController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\PromoService;

class PromosController extends Controller
{
    public function __construct(PromoService $promo_service)
    {
        $this->service = $promo_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $promos = $this->service->search($request->get('code'));
        return response()->json($promos);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $promos = $this->service->search($request->search);
        return response()->json($promos);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\PromoRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to create promo'], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $promo = $this->service->find($id);
        return response()->json($promo);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\PromoRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to update promo'], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return response()->json(['success' => 'Promo was deleted'], 200);
        }

        return response()->json(['error' => 'Unable to delete promo'], 500);
    }
}

resources/views/admin/promos/add.blade.php
@extends('admin.layouts.app', ['page' => 'promo'])

@section('title', 'Add New Promo')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Add New Promo
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" action="{{ route('admin.promos.store') }}">
        @csrf

        <div class="form-group">
            <label for="code">Code</label>
            <input type="text"
                class="form-control"
                name="code"
                required
                placeholder="Code"
                value="{{ old('code') }}"
                id="code"
            >
        </div>

        <div class="form-group">
            <label for="discount">Discount</label>
            <input type="number"
                class="form-control"
                name="discount"
                required
                placeholder="Discount"
                value="{{ old('discount') }}"
                step="any"
                id="discount"
            >
        </div>

        <div class="form-group">
            <label for="note">Note</label>
            <textarea class="form-control"
                name="note"
                id="note"
                required
                placeholder="Note"
            >{{ old('note') }}</textarea>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Submit
            </button>

            <a class="btn btn-sm btn-danger"
                href="{{ route('admin.promos.index') }}"
            >
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/promos/edit.blade.php
@extends('admin.layouts.app', ['page' => 'promo'])

@section('title', 'Edit Promo')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Edit Promo
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" action="{{ route('admin.promos.update', ['promo' => $promo->id]) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="code">Code</label>
            <input type="text"
                class="form-control"
                name="code"
                required
                placeholder="Code"
                value="{{ old('code', $promo->code) }}"
                id="code"
            >
        </div>

        <div class="form-group">
            <label for="discount">Discount</label>
            <input type="number"
                class="form-control"
                name="discount"
                required
                placeholder="Discount"
                value="{{ old('discount', $promo->discount) }}"
                step="any"
                id="discount"
            >
        </div>

        <div class="form-group">
            <label for="note">Note</label>
            <textarea class="form-control"
                name="note"
                id="note"
                required
                placeholder="Note"
            >{{ old('note', $promo->note) }}</textarea>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Update
            </button>

            <a class="btn btn-sm btn-danger"
                href="{{ route('admin.promos.index') }}"
            >
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/promos/index.blade.php
@extends('admin.layouts.app', ['page' => 'promo'])

@section('title', 'Promos')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Promos
        </div>

        <div class="col-6 text-right">
            <a class="btn btn-md btn-square btn-secondary"
                href="{{ route('admin.promos.create') }}"
            >
                Add New
            </a>
        </div>
    </div>
</div>

<div class="card-body m-2">
    <table class="table table-responsive-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Code</th>
                <th>Discount</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($promos as $promo)
                <tr>
                    <td>{{ $promo->id }}</td>
                    <td>{{ $promo->code }}</td>
                    <td>{{ $promo->discount }}</td>
                    <td>
                        <a class="btn btn-pill btn-sm btn-warning"
                            href="{{ route('admin.promos.edit', ['promo' => $promo->id]) }}"
                        >
                            <i class="fa fa-pencil-square-o"></i>
                        </a>

                        <form action="{{ route('admin.promos.destroy', ['promo' => $promo->id]) }}"
                            method="POST"
                            class="inline pointer"
                        >
                            @csrf
                            @method('DELETE')

                            <a class="btn btn-pill btn-sm btn-danger"
                                onclick="if (confirm('Are you sure?')) { this.parentNode.submit() }"
                            >
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{ $promos->links() }}
</div>
@endsection