routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return File::get(resource_path() . '/views/landing/index.html');
});

// Admin routes
Route::name('admin.')->prefix('admin')->namespace('Admin')->group(function () {
    Route::namespace('Auth')->middleware('guest:admin')->group(function () {
        // Login
        Route::get('/', 'LoginController@showLoginForm')->name('login');
        Route::post('/', 'LoginController@login');

        // Forget and reset Password
        Route::get('forgot-password', 'ForgotPasswordController@showLinkRequestForm')->name('forgot_password');
        Route::post('forgot-password', 'ForgotPasswordController@sendResetLinkEmail');
        Route::get('password/reset/{token}/{email?}', 'ResetPasswordController@showResetForm')->name('reset_password_link');
        Route::post('password/reset', 'ResetPasswordController@reset')->name('reset_password');
    });

    // Logged in admin user required
    Route::group(['middleware' => 'auth:admin'], function () {
        // Dashboard
        Route::get('/dashboard', 'AdminController@dashboard')->name('dashboard');

        Route::resource('addresses', 'AddressController');

        Route::resource('categories', 'CategoryController');

        Route::resource('customers', 'CustomerController');

        Route::resource('products', 'ProductController');

        Route::resource('notifications', 'NotificationController');

        Route::resource('orders', 'OrderController');

        Route::resource('promos', 'PromoController');

        // Profile
        Route::get('/profile', 'AdminController@profile')->name('profile');
        Route::post('/profile', 'AdminController@profileUpdate');
        Route::post('/password', 'AdminController@passwordUpdate')->name('password_update');

        // Logout
        Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
    });
});

app/Category.php
<?php

namespace App;

use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use SoftDeletes, LogsActivity;

    protected static $logFillable = true;

    protected static $logOnlyDirty = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'active'
    ];

    /**
     * Validation rules
     *
     * @return array
     **/
    public static function validationRules()
    {
        return [
            'name' => 'required|string',
            'description' => 'nullable|string',
            'active' => 'required|boolean',
//            'products' => 'required|array',
//            'products.*' => 'required|numeric|exists:products,id',
        ];
    }

    /**
     * Get the products for the Category.
     */
    public function products()
    {
        return $this->belongsToMany('App\Product');
    }

    /**
     * Returns the paginated list of resources
     *
     * @return \Illuminate\Pagination\Paginator
     **/
    public static function getList()
    {
        return static::paginate(10);
    }
}

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $table = "categories";

    public $primaryKey = "id";

    public $timestamps = true;

    public $fillable = [
		'id',
		'name',
		'description',
		'active',
		'created_at',
		'updated_at',
		'deleted_at',

    ];

    public static $rules = [
        // create rules
    ];

    // Category 
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Product;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    /**
     * Display a list of Categories.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::getList();

        return view('admin.categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new Category
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $products = Product::all();

        return view('admin.categories.add', compact('products'));
    }

    /**
     * Save new Category
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store()
    {
        $validatedData = request()->validate(Category::validationRules());

        unset($validatedData['products']);
        $category = Category::create($validatedData);

        $category->products()->sync(request('products'));

        return redirect()->route('admin.categories.index')->with([
            'type' => 'success',
            'message' => 'Category added'
        ]);
    }

    /**
     * Show the form for editing the specified Category
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $products = Product::all();

        $category->products = $category->products->pluck('id')->toArray();

        return view('admin.categories.edit', compact('category', 'products'));
    }

    /**
     * Update the Category
     *
     * @param \App\Category $category
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Category $category)
    {
        $validatedData = request()->validate(
            Category::validationRules($category->id)
        );

        unset($validatedData['products']);
        $category->update($validatedData);

        $category->products()->sync(request('products'));

        return redirect()->route('admin.categories.index')->with([
            'type' => 'success',
            'message' => 'Category Updated'
        ]);
    }

    /**
     * Delete the Category
     *
     * @param \App\Category $category
     * @return void
     */
    public function destroy(Category $category)
    {
        if ($category->products()->count()) {
            return redirect()->route('admin.categories.index')->with([
                'type' => 'error',
                'message' => 'This record cannot be deleted as there are relationship dependencies.'
            ]);
        }

        $category->delete();

        return redirect()->route('admin.categories.index')->with([
            'type' => 'success',
            'message' => 'Category deleted successfully'
        ]);
    }
}

app/Http/Controllers/Api/CategoriesController.php
<?php

namespace App\Http\Controllers\Api;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Services\CategoryService;

class CategoriesController extends Controller
{
    public function __construct(CategoryService $category_service)
    {
        $this->service = $category_service;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $categories = $this->service->paginated();
        return response()->json($categories);
    }

    /**
     * Display a listing of the resource searched.
     *
     * @return \Illuminate\Http\Response
     */
    public function search(Request $request)
    {
        $categories = $this->service->search($request->search);
        return response()->json($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  App\Http\Requests\CategoryRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $result = $this->service->create($request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to create category'], 500);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->service->find($id);
        return response()->json($category);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  App\Http\Requests\CategoryRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $result = $this->service->update($id, $request->except('_token'));

        if ($result) {
            return response()->json($result);
        }

        return response()->json(['error' => 'Unable to update category'], 500);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = $this->service->destroy($id);

        if ($result) {
            return response()->json(['success' => 'Category was deleted'], 200);
        }

        return response()->json(['error' => 'Unable to delete category'], 500);
    }
}

resources/views/admin/categories/add.blade.php
@extends('admin.layouts.app', ['page' => 'category'])

@section('title', 'Add New Category')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Add New Category
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" action="{{ route('admin.categories.store') }}">
        @csrf

        <div class="form-group">
            <label for="name">Name</label>
            <input type="text"
                class="form-control"
                name="name"
                required
                placeholder="Name"
                value="{{ old('name') }}"
                id="name"
            >
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control"
                name="description"
                id="description"
                required
                placeholder="Description"
            >{{ old('description') }}</textarea>
        </div>

        <div class="form-group">
            <label class="checkbox-inline">
                <input type="hidden" name="active" value="0">
                <input type="checkbox"
                    name="active"
                    value="1"
                    {{ old('active') == 1 ? 'checked' : '' }}
                >
                    Active
            </label>
        </div>

        <div class="form-group">
            <label for="products">Product</label>
            <select class="form-control"
                name="products[]"
                required
                multiple
                id="products"
            >
                @foreach ($products as $product)
                    <option value="{{ $product->id }}"
                        {{ is_array(old('products')) && in_array($product->id, old('products')) ? 'selected' : '' }}
                    >
                        {{ $product->name }}
                    </option>
                @endforeach
            </select>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Submit
            </button>

            <a class="btn btn-sm btn-danger"
                href="{{ route('admin.categories.index') }}"
            >
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app', ['page' => 'category'])

@section('title', 'Edit Category')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Edit Category
        </div>
    </div>
</div>

<div class="card-body m-2">
    <form role="form" method="POST" action="{{ route('admin.categories.update', ['category' => $category->id]) }}">
        @csrf
        @method('PUT')

        <div class="form-group">
            <label for="name">Name</label>
            <input type="text"
                class="form-control"
                name="name"
                required
                placeholder="Name"
                value="{{ old('name', $category->name) }}"
                id="name"
            >
        </div>

        <div class="form-group">
            <label for="description">Description</label>
            <textarea class="form-control"
                name="description"
                id="description"
                required
                placeholder="Description"
            >{{ old('description', $category->description) }}</textarea>
        </div>

        <div class="form-group">
            <label class="checkbox-inline">
                <input type="hidden" name="active" value="0">
                <input type="checkbox"
                    name="active"
                    value="1"
                    {{ old('active', $category->active) == 1 ? 'checked' : '' }}
                >
                    Active
            </label>
        </div>

        <div class="form-group">
            <label for="products">Product</label>
            <select class="form-control"
                name="products[]"
                required
                multiple
                id="products"
            >
                @foreach ($products as $product)
                    <option value="{{ $product->id }}"
                        {{ in_array($product->id, old('products', $category->products)) ? 'selected' : '' }}
                    >
                        {{ $product->name }}
                    </option>
                @endforeach
            </select>
        </div>

        <div class="card-footer">
            <button type="submit" class="btn btn-sm btn-primary">
                Update
            </button>

            <a class="btn btn-sm btn-danger"
                href="{{ route('admin.categories.index') }}"
            >
                Cancel
            </a>
        </div>
    </form>
</div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app', ['page' => 'category'])

@section('title', 'Categories')

@section('content')
<div class="card-header">
    <div class="row">
        <div class="col-6 pt-2 h5">
            <i class="fa fa-tint"></i>
            Categories
        </div>

        <div class="col-6 text-right">
            <a class="btn btn-md btn-square btn-secondary"
                href="{{ route('admin.categories.create') }}"
            >
                Add New
            </a>
        </div>
    </div>
</div>

<div class="card-body m-2">
    <table class="table table-responsive-sm">
        <thead>
            <tr>
                <th>#</th>
                <th>Name</th>
                <th>Action</th>
            </tr>
        </thead>

        <tbody>
            @forelse ($categories as $category)
                <tr>
                    <td>{{ $category->id }}</td>
                    <td>{{ $category->name }}</td>
                    <td>
                        <a class="btn btn-pill btn-sm btn-warning"
                            href="{{ route('admin.categories.edit', ['category' => $category->id]) }}"
                        >
                            <i class="fa fa-pencil-square-o"></i>
                        </a>

                        <form action="{{ route('admin.categories.destroy', ['category' => $category->id]) }}"
                            method="POST"
                            class="inline pointer"
                        >
                            @csrf
                            @method('DELETE')

                            <a class="btn btn-pill btn-sm btn-danger"
                                onclick="if (confirm('Are you sure?')) { this.parentNode.submit() }"
                            >
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="3">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{ $categories->links() }}
</div>
@endsection